############ DO NOT CHANGE THESE #################
SUPPORTED:=./src/
TOP_MODULE:=mkdcache_tb

############# User changes to be done below #################
DIR:=./src/common_bsv/:./src/common_verilog/:./tb/
TOP_DIR:= ./tb/
TOP_FILE:= ./dcache_tb.bsv

