############ DO NOT CHANGE THESE #################
SUPPORTED:=./src/
TOP_MODULE:=mkicache

############# User changes to be done below #################
DIR:= 
TOP_DIR:= ./src
TOP_FILE:= ./l1icache.bsv

